### ISSUE TITLE
export of simulation results to excel not possible with MoBi 7.2.0 portable

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/Forum#123]
if the simulation results in the attached Mobi file are tried to be exported via rightclick on the graph the following error appears. Screenshot and file is attached.
![mobi 7 2 export error](https://user-images.githubusercontent.com/25585248/34959531-38f9ac24-fa37-11e7-99d6-0f54a5422d71.PNG)
[test for Github.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/1632872/test.for.Github.zip)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileLoadException: Could not load file or assembly 'SX, Version=2.6.5.7, Culture=neutral, PublicKeyToken=882b9c044052e7f6' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'SX, Version=2.6.5.7, Culture=neutral, PublicKeyToken=882b9c044052e7f6'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Exception.GetStackTrace(Boolean needFileInfo)
   at System.Exception.get_StackTrace()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.FullStackTrace(Exception ex)
   at OSPSuite.Presentation.Services.ExceptionManager.showException(Exception ex)
   at OSPSuite.Presentation.Services.ExceptionManager.LogException(Exception ex)
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand)
   at OSPSuite.Presentation.MenuAndBars.MenuBarButton.Click()
   at OSPSuite.UI.Mappers.MenuBarButtonToBarItemMapperBase.<>c__DisplayClass1_0.<UpdateBarButtonItem>b__0(Object o, ItemClickEventArgs e)
   at DevExpress.XtraBars.BarItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarButtonItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.ClickLink(BarItemLink link)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.UnPressLink(BarItemLink link)
   at DevExpress.XtraBars.Controls.CustomLinksControl.OnMouseUp(MouseEventArgs e)
   at DevExpress.XtraBars.Controls.CustomPopupBarControl.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraBars.Controls.CustomControl.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by msevestre** [comment]
@tobiasK2001 Please use the latest version 7.2.1 of MoBi as you are using an outdated version (7.2.0). This will fix the problem

**Comment by msevestre** [comment]
And here is the link just in case to [7.2.1 Portable](https://github.com/Open-Systems-Pharmacology/MoBi/releases/download/v7.2.1.2/mobi-portable-setup.zip)

**Comment by tobiasK2001** [comment]
Ah, Thanks:-)
