### ISSUE TITLE
Pk-Sim Crash

### ISSUE THREAD

**Issue by JoseDavidGomez** [Open-Systems-Pharmacology/Forum#188]
Any Idea? This has happened several times this week,
IT has proven that it is not definetely a memory issue.

Application:
PK-Sim® 7.2.2 - Build 3

Exception of type 'System.OutOfMemoryException' was thrown.

Stack trace:
```
at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at System.Xml.XmlTextEncoder.Write(String text)
   at System.Xml.XmlTextWriter.WriteString(String text)
   at System.Xml.Linq.ElementWriter.WriteElement(XElement e)
   at System.Xml.Linq.XElement.WriteTo(XmlWriter writer)
   at System.Xml.Linq.XElement.Save(XmlWriter writer)
   at OSPSuite.Serializer.Xml.XmlHelper.XmlContentToByte(XElement element)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Serialize[TObject](TObject objectToSerialize)
   at PKSim.Core.Services.CompressedSerializationManager.Serialize[TObject](TObject objectToSerialize)
   at PKSim.Core.Services.CompressedSerializationManager.Serialize[TObject](TObject objectToSerialize, Boolean compress)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectToProjectMetaDataMapper.serializeContent[TObject](MetaDataWithContent`1 metaDataWithContent, TObject objectToSerialize, Boolean compress)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectToProjectMetaDataMapper.mapFrom(ParameterIdentification parameterIdentification)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectToProjectMetaDataMapper.<>c__DisplayClass4_0.<MapFrom>b__2(ParameterIdentification x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectToProjectMetaDataMapper.MapFrom(IPKSimProject project)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.projectMetaDataFrom(IPKSimProject project)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.Save(IPKSimProject projectToSave, ISession session)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.SaveSession(IWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.SaveProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.<>c__DisplayClass19_0.<saveProjectToFile>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by PavelBal** [comment]
This is not a memory issue of your system but of PK-Sim. The OSPS is currently 32-bit only, i.e., it can only address about 3.2 GiB memory. Once the memory demand grows higher (e.g. in a large population simulation), the programm crashes.

**Comment by msevestre** [comment]
@JoseDavidGomez What types of simulations / building blocks do you have in your project?
This problem can happen especially with many larger populations are being saved at the same time. 
Is this the case?

**Comment by msevestre** [comment]
@JoseDavidGomez Also I would suggest to report bug in the dedicated [PK-Sim issues](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues) tracker. Let's continue the discussion there. Thanks
