### ISSUE TITLE
unable to work with GENEDB_human

### ISSUE THREAD

**Issue by clitou** [Open-Systems-Pharmacology/Forum#236]
Dear all, 

I have downloaded the GENEDB_human database I set it in my applications settings (Utilities->Options->Application). However, I can't use the "Add Metabolizing Enzyme... (Database query)" option. I get the following error message: Application:
PK-Sim® 7.3.0.42

Not a valid password.

Stack trace:
```
at System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString constr, OleDbConnection connection)
   at System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)
   at System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
   at System.Data.OleDb.OleDbConnection.Open()
   at PKSim.Infrastructure.ORM.DAS.DAS.Connect(String dataProvider, String connectionString)
   at PKSim.Infrastructure.ORM.DAS.DAS.Connect(String dbName, String workgroupDb, String user, String password, DataProviders dataProvider)
   at PKSim.Infrastructure.ORM.DAS.DAS.Connect(String dbName, String user, String password, DataProviders dataProvider)
   at PKSim.Infrastructure.ORM.Core.Database.Connect(String databasePath)
   at PKSim.Infrastructure.ORM.Core.DatabaseDisposer..ctor(IDatabase database, String databasePath)
   at PKSim.Infrastructure.Services.ProteinExpressionsDatabasePathManager.ConnectToDatabaseFor(Species species)
   at PKSim.Presentation.Services.MoleculeExpressionTask`1.proteinFromQuery(TSimulationSubject simulationSubject, IndividualMolecule newMolecule)
   at PKSim.Presentation.Services.MoleculeExpressionTask`1.AddMoleculeTo[TMolecule](TSimulationSubject simulationSubject)
   at PKSim.Presentation.Presenters.Individuals.MoleculesPresenter`1.AddMolcule[TMolecule]()
   at OSPSuite.Presentation.MenuAndBars.ExecuteActionUICommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

Can you help me please? 
Thank you very much in advance for your help!
Chara

**Comment by msevestre** [comment]
@clitou Please make sure you are using the latest DB that was delivered with 7.3

https://github.com/Open-Systems-Pharmacology/Suite/releases/download/v7.3.0/GENEDB_human.mdb

We removed the password in the db so that everyone could access it. If you are using an old version however, the error would show.

Cheers,
Michael

**Comment by clitou** [comment]
Dear Michael, 

you are perfectly right-I was probably using an older version. 
Thank you once more for your kind help!
All the best,
Chara

**Comment by msevestre** [comment]
@clitou Awesome. Glad it worked
