### ISSUE TITLE
where can I download the compound template database

### ISSUE THREAD

**Issue by wuxuemei300** [Open-Systems-Pharmacology/Forum#241]
Hi,

I am studing how to do DDI with PK-Sim following the tutorial, it seems there is a compound template database, where can I download it ?

Thank you

Xuemei Wu

**Comment by msevestre** [comment]
@wuxuemei300 It's installed with the setup. Simply right click on any building block folder => load from template.

**Comment by wuxuemei300** [comment]
Thank, the problem is I right click to load it, it showed that can't find the template file. The installation maybe has problem, I will try to solve it. If not success, I will ask your help later.

Thank you so much

Xuemei Wu

**Comment by msevestre** [comment]
@wuxuemei300 Assuming you have solved your issue? Please reopen if you need more help. Thanks

**Comment by wuxuemei300** [comment]
Thank you for all the help, I checked it and found it is a computer specific problem. when it installed in other computer, there is no problem. I will reinstall it.

**Comment by wuxuemei300** [comment]
The problem still exists when I re-installed the software, it shows like this:
Application:
PK-Sim® 7.3.0.42

Microsoft Jet 数据库引擎找不到输入表或查询 'TAB_TEMPLATES'。 确定它是否存在，以及它的名称的拼写是否正确。(The Microsoft Jet database engine could not find the input table or query 'TAB_TEMPLATES'. Determine if it exists and if its name is spelled correctly.)

Stack trace:
```
at System.Data.OleDb.OleDbCommand.ExecuteCommandTextErrorHandling(OleDbHResult hr)
   at System.Data.OleDb.OleDbCommand.ExecuteCommandTextForSingleResult(tagDBPARAMS dbParams, Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteCommandText(Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteCommand(CommandBehavior behavior, Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteNonQuery()
   at PKSim.Infrastructure.ORM.DAS.DAS.ExecuteSQL(String sql)
   at PKSim.Infrastructure.Services.TemplateDatabaseConverter.convertDataBaseSchemaTo53(DAS database)
   at PKSim.Infrastructure.Services.TemplateDatabaseConverter.Convert(ITemplateDatabase templateDatabase)
   at PKSim.Infrastructure.Services.TemplateTaskQuery.establishConnection(TemplateDatabaseType templateDatabaseType)
   at PKSim.Infrastructure.Services.TemplateTaskQuery.AllTemplatesFor(TemplateDatabaseType templateDatabaseType, TemplateType templateType)
   at PKSim.Infrastructure.Services.TemplateTaskQuery.AllTemplatesFor(TemplateType templateType)
   at PKSim.Presentation.Presenters.TemplatePresenter.LoadFromTemplate[T](TemplateType templateType)
   at PKSim.Presentation.Services.BuildingBlockTask.LoadFromTemplate[TBuildingBlock](PKSimBuildingBlockType buildingBlockType)
   at PKSim.Presentation.Services.BuildingBlockTask`1.LoadFromTemplate(PKSimBuildingBlockType buildingBlockType)
   at PKSim.Presentation.Services.BuildingBlockTask`1.LoadFromTemplate()
   at PKSim.Presentation.Services.BuildingBlockTask`1.LoadSingleFromTemplate()
   at PKSim.Presentation.UICommands.LoadBuildingBlockFromTemplateUICommand`2.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```


How to solve it?

**Comment by wuxuemei300** [comment]
@msevestre can you help to fix it, please see above information I posted.

**Comment by msevestre** [comment]
@wuxuemei300 Not sure what is going on with your PC
Can you try the following:
1 - Close PKSim
2 - Go to file `C:\Users\xxxxx\AppData\Roaming\Open Systems Pharmacology\PK-Sim\` where xxxx is your windows username
3 - Delete the folder `7.3`
4 - Start PK-Sim and try again.

Let me know if this fixes the issue

**Comment by wuxuemei300** [comment]
Thank you very much, it works now.

Have a good day.

Xuemei wu

**Comment by nirav3223** [comment]
Hi,

I am getting the following error while loading the compound from templet.

cannot download templet located at "https://raw.githubusercontent.com/open-system-pharmacology/cimetidine-model/v1.1/cimetidine-model.json.

the request was aborted: could not created SSL/TLS secured channel.

**Comment by msevestre** [comment]
Hi @nirav3223 please create a new entry for this. It's good practice to not comment on an issue that is closed.
