### ISSUE TITLE
PK-Sim error message. Cannot save or open

### ISSUE THREAD

**Issue by LunaPrieto** [Open-Systems-Pharmacology/Forum#270]
I would need help with the following PK-Sim error. 
I just install the software on a new computer.
I can open the application but I cannot load previous projects or save new ones.
I will be very happy with any assistance on this. 
Thank you
/Luna

Application:
PK-Sim® 7.4.0.127

The type initializer for 'NHibernate.Cfg.Configuration' threw an exception.
-----------------------------------------------------
The type initializer for 'NHibernate.LoggerProvider' threw an exception.
-----------------------------------------------------
Unable to instantiate: NHibernate.Log4NetLoggerFactory
-----------------------------------------------------
Exception has been thrown by the target of an invocation.
-----------------------------------------------------
The type initializer for 'NHibernate.Log4NetLoggerFactory' threw an exception.
-----------------------------------------------------
Object reference not set to an instance of an object.

Stack trace:
```
at NHibernate.Log4NetLoggerFactory.GetGetLoggerMethodCall[TParameter]()
   at NHibernate.Log4NetLoggerFactory..cctor()
 --- End of inner exception stack trace ---
   at NHibernate.Log4NetLoggerFactory..ctor()
 --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at NHibernate.LoggerProvider.GetLoggerFactory(String nhibernateLoggerClass)
 --- End of inner exception stack trace ---
   at NHibernate.LoggerProvider.GetLoggerFactory(String nhibernateLoggerClass)
   at NHibernate.LoggerProvider..cctor()
 --- End of inner exception stack trace ---
   at NHibernate.LoggerProvider.LoggerFor(Type type)
   at NHibernate.Cfg.Configuration..cctor()
 --- End of inner exception stack trace ---
   at NHibernate.Cfg.Configuration.Reset()
   at PKSim.Infrastructure.Services.SessionFactoryProvider.createSqlLiteConfigurationFor(String dataSource)
   at PKSim.Infrastructure.Services.SessionFactoryProvider.OpenSessionFactoryFor(String dataSource)
   at OSPSuite.Infrastructure.Services.SessionManager.OpenFactoryFor(String fileName)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(IWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.<>c__DisplayClass16_0.<OpenProject>b__0()
   at PKSim.Infrastructure.Workspace.LoadProject(Action projectLoadAction)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.<>c__DisplayClass32_0.<openProjectFromFile>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by PavelBal** [comment]
I had the same problem couple of days before. If I recall correclty, it happened after some windows update...

After reinstalling the OSPS, everything started to work normally.

**Comment by LunaPrieto** [comment]
Thank you very much Pavel!
I will try to re-install it then.
/Luna

**Comment by PavelBal** [comment]
Warning - I can open the projects but I **cannot** save new!
