### ISSUE TITLE
Open and modify .expressionDB?

### ISSUE THREAD

**Issue by HenrikCordes** [Open-Systems-Pharmacology/Forum#273]
Dear All, 
in the recent update of PK-Sim, the access expression database (.mdb) was substituted with an .expressionDB database file.
Linking and accessing the new DB to PK-Sim works fine, but I can't open and modify the .expressionDB file with MS access. 

I didn't find any clues in the manual or other forum issues. 
A quick google search for the .expressionDB format lead me to this article and R package: https://www.ncbi.nlm.nih.gov/pubmed/29095940 
However, I couldn't make the connection between .expressionDB file and the package.

Is there a way to open and modify the .expressionDB as it was possible with the previous .mdb file? 
Which software is needed here?

Thank you for your help and advice 
Henrik

**Comment by msevestre** [comment]
Hi @HenrikCordes,

The database is a SQLite database. There are no built-in editor but plenty of free or open-source tools to do so.

Any addition to the database that would benefit the community would be obviously welcome

Good luck

**Comment by HenrikCordes** [comment]
Hi @msevestre ,

Thank you for the swift reply! 
I'll try SQLite than for accessing and modifying the DB. 

I spend some time working on the integration of human disease expression data, as well as expression data for the various species in PK-Sim which I would like to release in the near future.   

Kind regards,

**Comment by msevestre** [comment]
@HenrikCordes Excellent! Let us know if you need some help 

Check this one out: https://sqlitestudio.pl 

I am using DataGrip. Not free but very nice to work with https://www.jetbrains.com/datagrip/buy/#edition=personal

**Comment by HenrikCordes** [comment]
Dear All,
I updated PK-Sim to the 7.4 Version and I connected the .expressionDB via Options--> Applications.

Thank you for your help


@msevestre With the new DB connected to PK-Sim 7.4 and the I receive the following error: 

Application:
PK-Sim® 7.4.0.127

unable to open database file

Stack trace:
```
at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at PKSim.Infrastructure.ORM.DAS.DAS.Connect(String dataProvider, String connectionString)
   at PKSim.Infrastructure.ORM.DAS.DAS.Connect(String dbName, String workgroupDb, String user, String password, DataProviders dataProvider)
   at PKSim.Infrastructure.ORM.DAS.DAS.Connect(String dbName, String user, String password, DataProviders dataProvider)
   at PKSim.Infrastructure.ORM.Core.Database.Connect(String databasePath)
   at PKSim.Infrastructure.ORM.Core.DatabaseDisposer..ctor(IDatabase database, String databasePath)
   at PKSim.Infrastructure.Services.GeneExpressionsDatabasePathManager.ConnectToDatabaseFor(Species species)
   at PKSim.Presentation.Services.MoleculeExpressionTask`1.proteinFromQuery(TSimulationSubject simulationSubject, IndividualMolecule newMolecule)
   at PKSim.Presentation.Services.MoleculeExpressionTask`1.AddMoleculeTo[TMolecule](TSimulationSubject simulationSubject)
   at PKSim.Presentation.Presenters.Individuals.MoleculesPresenter`1.AddMolcule[TMolecule]()
   at OSPSuite.Presentation.MenuAndBars.ExecuteActionUICommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```
