### ISSUE TITLE
Unable to open parameter optimization BB

### ISSUE THREAD

**Issue by teutonicod** [Open-Systems-Pharmacology/Forum#287]
Dear all,

I am not anymore able to open the results of a parameter identification in PK-Sim. This already occurred me a couple of times, but I not sure which behavior generates this issue. I typically run the optimization, I rename the optimization BB and then I keep working with the model, opening and closing several simulations and optimization and everything works fine. Later on, I think when reopening the PK-Sim project, the optimization does not open anymore and gives me an error. But this does not happe systematically, with all the optimizations. Here below are the details of the error generated; do you have any clue what can generate this behavior?

By the way, the link provided in the error window (http://www.open-systems-pharmacology.org/pk-sim/issues) is not active, I think it should be updated.

Thanks a lot in advance for your suggestion!

Best,

Donato

*Application:*
*PK-Sim® 7.4.0.127*

*Object reference not set to an instance of an object.*

**Stack trace:**
```
at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationConfidenceIntervalPresenter.confidenceIntervalDTOFrom(ICache`2 confidenceInterval, IdentificationParameter identificationParameter, OptimizedParameterValue optimizedParameter)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationConfidenceIntervalPresenter.<>c__DisplayClass3_0.<mapFrom>b__2(<>f__AnonymousType0`2 <>h__TransparentIdentifier0)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationConfidenceIntervalPresenter.CalculateConfidenceIntervalFor(ParameterIdentification parameterIdentification, ParameterIdentificationRunResult runResult)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationCovarianceAnalysisPresenter.UpdateAnalysis()
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationMatrixAnalysisPresenter`1.set_SelectedRunResults(ParameterIdentificationRunResult value)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationMatrixAnalysisPresenter`1.UpdateAnalysisBasedOn(IAnalysable analysable)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationMatrixAnalysisPresenter`1.InitializeAnalysis(ISimulationAnalysis simulationAnalysis, IAnalysable analysable)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.createAnalysis(ISimulationAnalysis simulationAnalysis)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.Edit(TAnalyzable analyzable)
   at OSPSuite.Presentation.Presenters.SubjectPresenter`3.Edit(Object objectToEdit)
   at PKSim.Presentation.Core.SingleStartPresenterTask.StartForSubject[T](T subject)
   at OSPSuite.Presentation.UICommands.EditParameterIdentificationUICommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by Yuri05** [comment]
Hi Donato, I guess it's not possible to upload the project?

If so, can you describe your PI configuration as precise as possible:
 * Simulations and Observed data used
 * Which parameters were optimized? Incl. optimization settings (bounds, linked parameters, scale, ...)
 * Algorithm configuration (single/multiple start values/Calc methods variation; used algorithm, ...)
 * Which plots were created in the PI before the project was saved
Which project parts used in the PI (simulations, observed data, ...) did you modify (delete/rename/...) AFTER the PI was completed?

Can you also try to export the project to snapshot? (will result in the same error I guess)

**Comment by teutonicod** [comment]
Hi Juri, 

Thanks for your reply. No, unfortunately I cannot upload the project file.
So I was using detasets for 3 different species, with IV and PO for each species (6 datasets in total).
The data I used were individual profiles, and not average data, with 3 profiles for each dataset.
I used the default method for Monte Carlo and I tried to estimate Lipophilicity and clearance for all data, using the automatic test of different distribution model. Later I did not change anything in the building block but I just renamed the building block itself after the PI was completed.

I saved several snapshot in the last weeks, but I cannot load any of them (except just the first one created) since I get again the same error. I thought that snapshot could be used as backup, but if one component of the model is corrupt (simulation, PI,...) the whole upload gives an error?

Thanks again and sorry if I cannot provide more details about this issue. I will keep an eye on the next PIs :-).

Donato
